/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Dzina_Andreyeva' at '2/18/16 11:30 AM' with Gradle 2.6
 *
 * @author Dzina_Andreyeva, @date 2/18/16 11:30 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
